export type Tool = {
  slug: string;
  name: string;
  tagline: string;
  icon: string;
  live: boolean;
};

export const tools: Tool[] = [
  {
    slug: 'palette-extractor',
    name: 'Palette Extractor',
    tagline: 'Drop an image in. Get all the colors back as hex codes.',
    icon: '🎨',
    live: true,
  },
  {
    slug: 'demake',
    name: 'Demake',
    tagline: 'Turn a real photo into a retro console screenshot.',
    icon: '👾',
    live: true,
  },
  {
    slug: 'crt',
    name: 'CRT-ify',
    tagline: 'Makes everything look like it came off a 1987 TV.',
    icon: '📺',
    live: true,
  },
  {
    slug: 'pixel-text',
    name: 'Pixel Text',
    tagline: 'Type something. Download it as a pixel font PNG.',
    icon: '🅰️',
    live: true,
  },
  {
    slug: 'dither',
    name: 'Dithering Studio',
    tagline: 'Bayer and Floyd-Steinberg dithering. Old tricks, still good.',
    icon: '▒',
    live: true,
  },
  {
    slug: 'upscale',
    name: 'Pixel Upscaler',
    tagline: 'Blow up sprites without turning them into blurry mush.',
    icon: '⬆',
    live: true,
  },
  {
    slug: 'ascii',
    name: 'ASCII Art',
    tagline: 'Your photo, rebuilt out of keyboard characters.',
    icon: '▓',
    live: true,
  },
  {
    slug: 'avatar',
    name: '8-bit Avatar',
    tagline: 'Stick a name in. Get a unique pixel face back.',
    icon: '◉',
    live: true,
  },
  {
    slug: 'vhs',
    name: 'VHS Effect',
    tagline: 'Your photo + a broken VHS deck. Bad tape, good vibes.',
    icon: '📼',
    live: true,
  },
  {
    slug: 'sfx',
    name: '8-bit SFX',
    tagline: 'Coin sounds, explosions, lasers. All in your browser.',
    icon: '🔊',
    live: true,
  },
  {
    slug: 'sprite-slicer',
    name: 'Sprite Slicer',
    tagline: 'Chop a sprite sheet into individual frames.',
    icon: '✂️',
    live: true,
  },
  {
    slug: 'badge',
    name: 'Badge Maker',
    tagline: 'Retro achievement badges. Slap them on your README.',
    icon: '🏆',
    live: true,
  },
  {
    slug: 'color',
    name: '8-bit Color',
    tagline: 'Paste any hex code. See it in every retro palette.',
    icon: '💎',
    live: true,
  },
  {
    slug: 'bootscreen',
    name: 'Boot Screen',
    tagline: 'Fake a DOS boot screen. Makes a great wallpaper.',
    icon: '💾',
    live: true,
  },
  {
    slug: 'gradient',
    name: 'Retro Gradient',
    tagline: 'Gradients that only use colors from actual old hardware.',
    icon: '🌈',
    live: true,
  },
  {
    slug: 'sticker',
    name: 'Sticker Maker',
    tagline: 'Thick outline on any image. Instant sticker effect.',
    icon: '⭐',
    live: true,
  },
  {
    slug: 'noise',
    name: 'Pixel Noise',
    tagline: 'Tileable noise textures. Looks like static, tiles perfectly.',
    icon: '░',
    live: true,
  },
  {
    slug: 'waveform',
    name: 'Waveform Art',
    tagline: 'See what your audio looks like. Export it as pixel art.',
    icon: '🎵',
    live: true,
  },
  {
    slug: 'sprite-painter',
    name: 'Sprite Painter',
    tagline: 'Draw pixel art from scratch. Tiny canvas, big fun.',
    icon: '🖌',
    live: true,
  },
  {
    slug: 'glitch',
    name: 'Glitch Art',
    tagline: 'Channel shifts, pixel sorting, and general image chaos.',
    icon: '⚡',
    live: true,
  },
  {
    slug: 'bitcrusher',
    name: 'Bit Crusher',
    tagline: 'Make audio sound like a Game Boy.',
    icon: '📻',
    live: true,
  },
  {
    slug: 'qr-pixel',
    name: 'Pixel QR',
    tagline: 'QR codes that look like they belong here.',
    icon: '▣',
    live: true,
  },
  {
    slug: 'console-frame',
    name: 'Console Frame',
    tagline: 'Wrap any image in a Game Boy / GBA / NES screen frame.',
    icon: '🎮',
    live: true,
  },
  {
    slug: 'color-ramp',
    name: 'Color Ramp',
    tagline: 'Two hex codes in. A smooth retro palette between them.',
    icon: '🌓',
    live: true,
  },
  {
    slug: 'pattern-tile',
    name: 'Pattern Tile',
    tagline: 'Seamless pixel patterns for backgrounds and tiles.',
    icon: '▦',
    live: true,
  },
  {
    slug: 'sprite-animator',
    name: 'Sprite Animator',
    tagline: 'Upload frames. Preview them looping.',
    icon: '🎞',
    live: true,
  },
  {
    slug: 'pixel-clock',
    name: 'Pixel Clock',
    tagline: 'A live clock drawn in pixel art. Changes every second.',
    icon: '⏰',
    live: true,
  },
  {
    slug: 'type-tester',
    name: 'Type Tester',
    tagline: 'See your text in a bunch of retro pixel fonts at once.',
    icon: '✏',
    live: true,
  },
  // ── New tools batch 2 ──────────────────────────────────────────────────────
  {
    slug: 'pixelate',
    name: 'Pixelate',
    tagline: 'Turn any photo into chunky pixel art. Slide to control the block size.',
    icon: '⊞',
    live: true,
  },
  {
    slug: 'favicon',
    name: 'Favicon Maker',
    tagline: 'Draw a 16×16, 32×32 or 48×48 icon and download it as PNG.',
    icon: '🔖',
    live: true,
  },
  {
    slug: 'palette-db',
    name: 'Retro Palette DB',
    tagline: 'Every classic hardware palette — NES, Game Boy, C64, PICO-8 and more.',
    icon: '🗄',
    live: true,
  },
  {
    slug: 'snake',
    name: 'Snake',
    tagline: "Classic snake. Eat food, grow longer, don't bite yourself.",
    icon: '🐍',
    live: true,
  },
  {
    slug: 'breakout',
    name: 'Breakout',
    tagline: 'Break all the bricks with a bouncing ball. Classic arcade action.',
    icon: '🧱',
    live: true,
  },
  {
    slug: 'life',
    name: 'Game of Life',
    tagline: "Conway's cellular automaton. Draw cells and watch evolution unfold.",
    icon: '🔬',
    live: true,
  },
  {
    slug: 'chiptune',
    name: 'Chiptune Sequencer',
    tagline: 'Make 8-bit music in your browser. Square waves, sawtooth, triangle.',
    icon: '🎹',
    live: true,
  },
  {
    slug: 'pixel-banner',
    name: 'Pixel Banner',
    tagline: 'Scrolling pixel font text. Download as PNG for READMEs and profiles.',
    icon: '📢',
    live: true,
  },
  {
    slug: 'matrix',
    name: 'Matrix Rain',
    tagline: 'The digital rain. Customize colors and characters, capture a screenshot.',
    icon: '🌧',
    live: true,
  },
  {
    slug: 'char-editor',
    name: 'Char Editor',
    tagline: 'Draw 8×8, 16×16 or 32×32 pixel characters and icons. Export as PNG or CSS.',
    icon: '◼',
    live: true,
  },
  {
    slug: 'css-pixels',
    name: 'CSS Pixel Art',
    tagline: 'Draw a 16×16 sprite and export it as pure CSS box-shadow code.',
    icon: '⌨',
    live: true,
  },
  {
    slug: 'mosaic',
    name: 'Pixel Mosaic',
    tagline: 'Turn photos into tile mosaics of squares, circles, or diamonds.',
    icon: '▦',
    live: true,
  },
  {
    slug: 'name-card',
    name: 'Pixel Name Card',
    tagline: 'Generate an 8-bit profile card. Download and use it anywhere.',
    icon: '🪪',
    live: true,
  },
  {
    slug: 'color-wheel',
    name: 'Color Harmony',
    tagline: 'Build palettes using complementary, triadic, and analogous color rules.',
    icon: '🎡',
    live: true,
  },
  {
    slug: 'sprite-flip',
    name: 'Sprite Flip',
    tagline: 'Mirror, rotate, and scale pixel art sprites without blurring a pixel.',
    icon: '↔',
    live: true,
  },
  // ── New tools batch 3 ──────────────────────────────────────────────────────
  {
    slug: 'contrast-checker',
    name: 'Contrast Checker',
    tagline: 'WCAG contrast ratios, plus which retro palette colors actually pass.',
    icon: '◐',
    live: true,
  },
  {
    slug: 'sprite-packer',
    name: 'Sprite Packer',
    tagline: 'Pack loose sprite images into one atlas PNG + JSON coordinate map.',
    icon: '▤',
    live: true,
  },
  {
    slug: 'tilemap-editor',
    name: 'Tilemap Editor',
    tagline: 'Paint a tile map from any tileset. Export PNG and JSON.',
    icon: '▧',
    live: true,
  },
  {
    slug: 'gif-frames',
    name: 'GIF Frame Extractor',
    tagline: 'Drop an animated GIF, get every frame back as PNGs.',
    icon: '🎬',
    live: true,
  },
  {
    slug: 'pong',
    name: 'Pong',
    tagline: 'The one that started it all. Versus CPU or 2-player local.',
    icon: '🏓',
    live: true,
  },
  {
    slug: '256',
    name: '256',
    tagline: "2048's mechanics, Station255's number. Merge tiles, reach 256.",
    icon: '🔢',
    live: true,
  },
];
